# server application
server.port: 16000
spring.application.name: =artifactId=
spring.mvc.favicon.enabled: false

server.use-forward-headers: true
server.tomcat.protocol_header: X-Forwarded-Proto
server.tomcat.remote_ip_header: X-Forwarded-For
server.tomcat.port-header: X-Forwarded-Port

spring.devtools.enabled: true
spring.http.encoding.charset: UTF-8
spring.http.encoding.force: true
spring.http.encoding.enabled: true

spring:
  mvc: 
    static-path-pattern: /**
  resources:
    static-locations: 
      - classpath:/static
      - classpath:/public
      - classpath:/resources
      - classpath:/META-INF/resources
      - file:${site.store.root}
  profiles:
    active: =build.profile.id=
  freemarker:
    template-loader-path: 
      - classpath:/templates
      - file:./templates
    cache: false
    checkTemplateLocation: false
    settings:
      classic_compatible: true #处理空值
      template_exception_handler: rethrow
      template_update_delay: 0
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
  jpa:
    database: mysql
    show-sql: false
    hibernate.ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      hibernate.cache.use_second_level_cache: false
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: cache/hibernate_indexes

#spring.cache.type: redis
spring.cache.type: jcache
spring.cache.jcache.config: classpath:ehcache3.xml

spring.servlet.multipart.max-file-size: 5MB
#site.theme: [default|card]
site.theme: card
site.store.size: 2  #上传文件最大2M