# server application
server.host: 127.0.0.1
server.servlet.context-path: /

# logger, to see logback-spring.xml
logging.level: INFO
logging.level.app: INFO

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.12.26.92:3306/sz?useSSL=false&characterEncoding=utf8
    username: root
    password: root

site.store.root: C:\\uzblog\\
